@api = http://localhost:3000/orders

###

GET {{api}}

###

GET {{api}}/5

###

POST {{api}}

Content-Type: application/json

{
    "fecha": "2023-02-06",
    "orders": "Nuevo pedido para cliente potencial "
}


###

DELETE {{api}}/1


###

PUT {{api}}/2

Content-Type: application/json

{
    "orders": "Pedido para Marisa Aneas"
}


