@api = http://localhost:3000/products

GET {{api}}

###

GET {{api}}/1

###

GET {{api}}/count

###

POST {{api}}

Content-Type: application/json

{
    "title": "Jabon",
    "description": "3 unidades",
    "price": 250 
}


###

DELETE {{api}}/3