@api = http://localhost:3000/products2
###

GET {{api}}

###

GET {{api}}/2

###

GET {{api}}/count

###

POST {{api}}

content-type: application/json

{
    "title": "Jabon de tocador",
    "description": "3 unidades",
    "price": 250 
}


###

DELETE {{api}}/6


###

PUT {{api}}/3
content-type: application/json

{
    "price": 460
}